function circlesToFile(fid, center, radii, metric, polarity)
    for i = 1:length(radii)
       fprintf(fid, ...
           '{"x":%d,"y":%d,"radius":%d,"strength":%f,"polarity":"%s"}', ...
           round(center(i, 1)), ...
           round(center(i, 2)), ...
           round(radii(i)), ...
           metric(i), ...
           polarity);

        if i ~= length(radii)
        	fprintf(fid, ',');
        end
    end
end

